apiVersion: v1
kind: Pod
metadata:
  name: app3
  namespace: default
spec:
  containers:
  - name: app3
    image: app3:3.0.0
    imagePullPolicy: Never
    resources:
      limits:
        memory: "200Mi"