apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1-ns
spec:
  selector:
    app: app1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000
